general {
    after_sleep_cmd = hyprctl dispatch dpms on             # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150                                             # 2.5min
    on-timeout = omarchy-launch-screensaver                   # start screensaver
}
